site_name: CGPClient
site_url: https://nhs-ngs.github.io/cgpclient
repo_name: NHS-NGS/cgpclient
site_dir: public

nav:
  - Home: index.md
  - Set up:
    - Set up: set_up/set_up.md
    - Register: set_up/register.md
    - Authenticate: set_up/auth.md
    - Configuration: set_up/config.md
  - Uses:
    - Uses: uses/uses.md
    - Fetching Files: uses/fetching_files.md
    - dWGS: uses/upload_dragen_run.md
  - Training:
    - Training: training/training.md
    - dWGS Upload: training/dwgs_upload.md
    - IGV.js Integration: training/htsget-igv-integration.md
  - Contributing: contributing.md

theme:
  name: material
  repo_url: https://github.com/NHS-NGS/cgpclient
  repo_name: GitHub
  custom_dir: docs/assets/overrides
  language: en
  logo: assets/img/GEL_logo_RGB_Light.png
  favicon: assets/img/GEL_logo_RGB_Dark.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Avenir LT Pro
    code: Roboto Mono
  features:
    - navigation.expand
    - content.code.annotate
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.share
    - toc.follow
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-884NKBZR97

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - abbr
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - assets/includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: True
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 2

plugins:
  - search:
      lang: en
  - mermaid2
  - mkdocstrings:
      default_handler: python

copyright: Copyright &copy; 2022-2025 Genomics England Limited
