#!/usr/bin/env python3

import argparse
import sys
from pathlib import Path

import yaml  # type: ignore

from cgpclient.client import CGPClient, CGPReferrals
from cgpclient.fhir import FHIRConfig  # type: ignore
from cgpclient.utils import setup_logger


def parse_args(args: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=("List NGIS referrals associated with the supplied identifiers")  # noqa: E501
    )
    parser.add_argument(
        "-r",
        "--referral_id",
        type=str,
        help="NGIS referral ID, e.g r30000000001",
    )
    parser.add_argument(
        "-p",
        "--participant_id",
        type=str,
        help="NGIS participant ID, e.g p12345678303",
    )
    parser.add_argument("-s", "--sample_id", type=str, help="Sample identifier")  # noqa: E501
    parser.add_argument(
        "-id",
        "--run_id",
        type=str,
        help=("Unique identifier for the sequencing run"),
    )
    parser.add_argument(
        "-t",
        "--tumour_id",
        type=str,
        help="Histopathology or SIHMDS identifier for a tumour sample",
    )
    parser.add_argument(
        "-o",
        "--ods_code",
        type=str,
        help="ODS code for your organisation",
    )
    parser.add_argument(
        "-c",
        "--clinical_indication",
        type=str,
        help='Clinical indication code ("R number")',
    )
    parser.add_argument(
        "-a",
        "--all",
        action="store_true",
        help="Show all referral details rather than summary",
    )
    parser.add_argument(
        "-host",
        "--api_host",
        type=str,
        help="API host base URL (default api.service.nhs.uk)",
        default="api.service.nhs.uk",
    )
    parser.add_argument(
        "-api",
        "--api_name",
        type=str,
        help="API name (e.g. genomic-data-access)",
    )
    parser.add_argument(
        "-over",
        "--override_api_base_url",
        type=bool,
        help="Override the default API base URLs in all relevant URLs",
        default=False,
    )
    parser.add_argument(
        "-k",
        "--api_key",
        type=str,
        help=(
            "NHS APIM API key from application registered in "
            "https://digital.nhs.uk/developer"
        ),
    )
    parser.add_argument(
        "-pem",
        "--private_key_pem_file",
        type=Path,
        help=(
            "Path to private key PEM file, the corresponding public key "
            "must have been shared with NHS APIM"
        ),
    )
    parser.add_argument(
        "-kid",
        "--apim_kid",
        type=str,
        help=(
            "NHS APIM Keypair Identifier (KID), must have been shared "
            "with NHS APIM (default 'test-1')"
        ),
        default="test-1",
    )
    parser.add_argument(
        "-pp",
        "--pretty_print",
        action="store_true",
        help="Pretty print JSON output",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print verbose output",
    )
    parser.add_argument(
        "-vv",
        "--debug",
        action="store_true",
        help="Print debugging output",
    )
    parser.add_argument(
        "-cfg",
        "--config_file",
        type=Path,
        help="Configuration YAML file (default ~/.cgpclient/config.yaml)",
        default=Path.home() / ".cgpclient/config.yaml",
    )
    parser.add_argument(
        "-w",
        "--workspace_id",
        type=str,
        help="FHIR server workspace ID",
    )
    parser.add_argument(
        "-pv",
        "--pivot",
        action="store_true",
        help="Pivot file listing",
    )
    parser.add_argument(
        "--start_date", help="Start date in ISO format (e.g. 2025-08-01)"
    )
    parser.add_argument("--end_date", help="End date in ISO format \\(e.g. 2025-08-31)")

    parsed: argparse.Namespace = parser.parse_args(args)

    if parsed.config_file and parsed.config_file.is_file():
        # if we're passed a config file use it as default values
        # and then reparse
        config: dict = yaml.safe_load(parsed.config_file.read_text(encoding="utf-8"))  # noqa: E501
        parser.set_defaults(**config)
        parsed = parser.parse_args(args)

    return parsed


def main(cmdline_args: list[str]) -> None:
    args: argparse.Namespace = parse_args(cmdline_args)

    setup_logger(verbose=args.verbose, debug=args.debug)

    config: FHIRConfig = FHIRConfig(
        ods_code=args.ods_code,
        referral_id=args.referral_id,
        participant_id=args.participant_id,
        tumour_id=args.tumour_id,
        clinical_indication_code=args.clinical_indication,
        run_id=args.run_id,
        sample_id=args.sample_id,
        workspace_id=args.workspace_id,
        start_date=args.start_date,
        end_date=args.end_date,
    )

    client: CGPClient = CGPClient(
        api_host=args.api_host,
        api_name=args.api_name,
        api_key=args.api_key,
        private_key_pem=args.private_key_pem_file,
        apim_kid=args.apim_kid,
        override_api_base_url=args.override_api_base_url,
        fhir_config=config,
    )

    referrals: CGPReferrals = client.get_referrals()

    referrals.print_table(
        summary=not args.all,
        sort_by="last_updated",
        pivot=args.pivot,
        include_header=True,
        output=sys.stdout,
    )


if __name__ == "__main__":
    main(sys.argv[1:])
